version: '3'
services:
  api:
    build: ./gin
    container_name: gin_container
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./gin/src/api:/go/src/api
  vuejs:
    build: ./vuejs
    container_name: vuecli3
    tty: true
    ports:
      - "18080:3000"
    volumes:
      - ./vuejs/src:/app
    # stdin_open: true
  mysql:
    build: ./mysql
    container_name: mysql_container
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: Tribu242
      TZ: 'Asia/Tokyo'
    # command: mysql --defaults-extra-file=/tmp/dbaccess.cnf gin_test < /tmp/schema.sql
    ports:
    - 3306:3306
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf.d:/etc/mysql/conf.d
    - ./mysql/sql:/docker-entrypoint-initdb.d
    - ./mysql/schema:/tmp
